accordion-padding = 0
after-login-command = []
after-startup-command = []
automatically-unhide-macos-hidden-apps = true
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse window-lazy-center"]
start-at-login = false

[gaps.inner]
horizontal = 0
vertical = 0

[gaps.outer]
bottom = 0
left = 0
right = 0
top = 0

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-d = "workspace d"
alt-e = "workspace e"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-q = "workspace q"
alt-shift-0 = "balance-sizes"
alt-shift-1 = ["move-node-to-workspace 1"]
alt-shift-2 = ["move-node-to-workspace 2"]
alt-shift-3 = ["move-node-to-workspace 3"]
alt-shift-4 = ["move-node-to-workspace 4"]
alt-shift-d = ["move-node-to-workspace d"]
alt-shift-e = ["move-node-to-workspace e"]
alt-shift-equal = "resize smart +100"
alt-shift-f = "fullscreen"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-minus = "resize smart -100"
alt-shift-q = ["move-node-to-workspace q"]
alt-shift-t = ["move-node-to-workspace t"]
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-w = ["move-node-to-workspace w"]
alt-t = "workspace t"
alt-tab = "workspace-back-and-forth"
alt-w = "workspace w"
cmd-shift-e = "layout tiles h_accordion tiling"
cmd-shift-f = ["layout floating tiling"]
cmd-shift-h = "join-with left"
cmd-shift-l = "join-with right"
cmd-shift-r = ["flatten-workspace-tree", "mode main"]

[mode.service.binding]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
esc = ["reload-config", "mode main"]

[[on-window-detected]]
check-further-callbacks = false
run = ["layout floating"]

[on-window-detected.if]
app-id = "com.apple.Safari"
window-title-regex-substring = "^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$"

[[on-window-detected]]
check-further-callbacks = false
run = ["layout tiling", "move-node-to-workspace e"]

[on-window-detected.if]
app-id = "com.apple.systempreferences"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 1"]

[on-window-detected.if]
app-id = "com.apple.Safari"

[[on-window-detected]]
check-further-callbacks = false
run = ["layout tiling", "move-node-to-workspace d"]

[on-window-detected.if]
app-id = "com.mitchellh.ghostty"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace q"]

[on-window-detected.if]
app-id = "com.electron.dockerdesktop"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace q"]

[on-window-detected.if]
app-id = "org.jkiss.dbeaver.core.product"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 2"]

[on-window-detected.if]
app-id = "com.openai.chat"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 4"]

[on-window-detected.if]
app-id = "abnerworks.Typora"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 4"]

[on-window-detected.if]
app-id = "com.apple.iWork.Pages"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 3"]

[on-window-detected.if]
app-id = "ru.keepcoder.Telegram"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace e"]

[on-window-detected.if]
app-id = "com.apple.finder"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 3"]

[on-window-detected.if]
app-id = "ch.protonmail.desktop"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace e"]

[on-window-detected.if]
app-id = "com.apple.AppStore"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace 3"]

[on-window-detected.if]
app-id = "com.spotify.client"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace t"]

[on-window-detected.if]
app-id = "kontur.talk"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace w"]

[on-window-detected.if]
app-id = "com.cisco.secureclient.gui"

[[on-window-detected]]
check-further-callbacks = false
run = ["move-node-to-workspace w"]

[on-window-detected.if]
app-id = "com.liguangming.Shadowrocket"

[workspace-to-monitor-force-assignment]
1 = "main"
2 = "secondary"
3 = "secondary"
4 = "main"
d = "main"
e = "secondary"
q = "secondary"
t = "secondary"
w = "secondary"
