return {
	{
		"Shatur/neovim-ayu",
		priority = 1000,
		lazy = false,
		config = function()
			-- Quiet Ayu Glass: прозрачный редактор, непрозрачные всплывающие окна.
			local colors = {
				bg = "#0d1017",
				fg = "#bfbdb6",
				muted = "#858d9c",
				border = "#303847",
				selection = "#273747",
				accent = "#73d0ff",
				error = "#f07178",
				warn = "#e6b450",
				success = "#aad94c",
				strings = "#95e6cb",
			}

			require("ayu").setup({
				mirage = false,
				terminal = true,
				overrides = {
					Normal = { fg = colors.fg, bg = "NONE" },
					NormalNC = { fg = colors.fg, bg = "NONE" },
					SignColumn = { bg = "NONE" },
					FoldColumn = { bg = "NONE" },

					Comment = { fg = colors.muted },
					String = { fg = colors.strings },
					["@string"] = { link = "String" },
					Function = { fg = colors.accent },
					["@function"] = { link = "Function" },
					["@function.call"] = { link = "Function" },
					Directory = { fg = colors.accent },
					Title = { fg = colors.accent, bold = true },
					Number = { fg = colors.warn },
					Keyword = { fg = colors.warn },
					LineNr = { fg = colors.muted },
					CursorLine = { bg = colors.bg },
					CursorLineNr = { fg = colors.accent, bold = true },
					Search = { bg = colors.selection, fg = colors.fg, bold = true },

					NormalFloat = { fg = colors.fg, bg = colors.bg },
					FloatBorder = { bg = colors.bg, fg = colors.border },
					Pmenu = { bg = colors.bg, fg = colors.fg },
					PmenuSel = { bg = colors.selection, fg = colors.fg, reverse = false },
					Visual = { bg = colors.selection },
					WinSeparator = { fg = colors.border, bg = "NONE" },
					FloatTitle = { fg = colors.accent, bg = colors.bg, bold = true },
					DiagnosticError = { fg = colors.error },
					DiagnosticWarn = { fg = colors.warn },
					DiagnosticInfo = { fg = colors.accent },
					DiagnosticHint = { fg = colors.strings },
					DiagnosticOk = { fg = colors.success },
					MiniIconsBlue = { fg = colors.accent },
					MiniIconsCyan = { fg = colors.strings },
					MiniIconsGreen = { fg = colors.success },
					MiniIconsGrey = { fg = colors.muted },
					MiniIconsOrange = { fg = colors.warn },
					MiniIconsPurple = { fg = colors.accent },
					MiniIconsRed = { fg = colors.error },
					MiniIconsYellow = { fg = colors.warn },
					FylerNormal = { link = "Normal" },
					FylerNormalNC = { link = "NormalNC" },
					FylerBorder = { link = "FloatBorder" },
					NeoTreeNormal = { link = "Normal" },
					NeoTreeNormalNC = { link = "NormalNC" },
					NeoTreeFloatNormal = { link = "NormalFloat" },
					NeoTreeFloatBorder = { link = "FloatBorder" },
					SnacksInputNormal = { link = "NormalFloat" },
					SnacksInputBorder = { link = "FloatBorder" },
					SnacksInputTitle = { link = "FloatTitle" },
					SnacksPicker = { link = "NormalFloat" },
					SnacksPickerBorder = { link = "FloatBorder" },
					SnacksPickerTitle = { link = "FloatTitle" },

					TelescopeNormal = { link = "NormalFloat" },
					TelescopeBorder = { link = "FloatBorder" },
					TelescopePromptNormal = { link = "NormalFloat" },
					TelescopeResultsNormal = { link = "NormalFloat" },
					TelescopePreviewNormal = { link = "NormalFloat" },
					TelescopePromptBorder = { link = "FloatBorder" },
					TelescopeResultsBorder = { link = "FloatBorder" },
					TelescopePreviewBorder = { link = "FloatBorder" },
					TelescopePromptTitle = { link = "Title" },
					TelescopeResultsTitle = { link = "Title" },
					TelescopePreviewTitle = { link = "Title" },
				},
			})

			vim.cmd.colorscheme("ayu")
		end,
	},
}
